CREATE TABLE locksley_stocks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_time TEXT NOT NULL
    price_open TEXT NOT NULL,
    price_high TEXT NOT NULL,
    price_low TEXT NOT NULL,
    price_close TEXT NOT NULL
); 